services:
  - type: web
    name: suno-pocket-studio
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: SUNOAPI_KEY
        sync: false
